import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Group from '../src/components/group';
import Box from '@mui/material/Box';
import GroupComponent from '../src/components/GroupComponent';
import ims from "../src/components/download.jpg"


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <GroupComponent />
        {/* <img src="/countries/GroupA/sn.svg" /> */}
      </main>

    </div>


  )
}
